server:
  port: 7002
  error:
    include-message: always

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: recommendations
          contentType: application/json
          group: recommendationsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          default-broker-port: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true

logging:
  level:
    root: info
    com.thatveryfewthings: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
