server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: oauth2-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth2/**

        - id: oauth2-login
          uri: lb://auth-server
          predicates:
            - Path=/login/**

        - id: oauth2-error
          uri: lb://auth-server
          predicates:
            - Path=/error/**

        - id: product-composite
          uri: lb://product-composite
          predicates:
            - Path=/product-composite/**

        - id: product-composite-swagger-ui
          uri: lb://product-composite
          predicates:
            - Path=/openapi/**

        - id: product-composite-swagger-ui-webjars
          uri: lb://product-composite
          predicates:
            - Path=/webjars/**

        - id: eureka-api
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-index
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-resources
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        - id: host_route_200
          uri: https://httpstat.us
          predicates:
            - Host=i.feel.lucky:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/200

        - id: host_route_418
          uri: https://httpstat.us
          predicates:
            - Host=im.a.teapot:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/418

        - id: host_route_501
          uri: https://httpstat.us
          predicates:
            - Path=/headerrouting/**
          filters:
            - SetPath=/501
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.auth-server.host}:${app.auth-server.port}

app:
  product-service:
    host: product

  recommendation-service:
    host: recommendation

  review-service:
    host: review

  product-composite-service:
    host: product-composite

  auth-server:
    host: localhost
    port: 9999

  eureka-server: localhost
  eureka-username: username
  eureka-password: password

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
