server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: product
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: products
          contentType: application/json
          group: productsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          default-broker-port: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true

app:
  eureka-server: localhost
  eureka-username: username
  eureka-password: password

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    root: info
    com.thatveryfewthings: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

