server:
  port: 7003
  error:
    include-message: always

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      # TODO: For a production environment this should be set to "none"!
      ddl-auto: update
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://localhost/review-db
    username: user
    password: secret
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: reviews
          content-type: application/json
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          default-broker-port: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true

app:
  jdbc-thread-pool-size: 10
  jdbc-task-queue-size: 100

logging:
  level:
    root: info
    com.thatveryfewthings: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
