server:
  port: 7003
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      # TODO: For a production environment this should be set to "none"!
      ddl-auto: update
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://localhost/review-db
    username: user
    password: secret

logging:
  level:
    root: info
    com.thatveryfewthings: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
