server:
  port: 7003
  error:
    include-message: always

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      # TODO: For a production environment this should be set to "none"!
      ddl-auto: update
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://localhost/review-db
    username: user
    password: secret
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: reviews
          contentType: application/json
          group: reviewsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
        bindings:
          messageProcessor-in-0:
            consumer:
              enableDlq: true

app:
  jdbc-thread-pool-size: 10
  jdbc-task-queue-size: 100

logging:
  level:
    root: info
    com.thatveryfewthings: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
